---

- hosts: development
  gather_facts: false
  become: yes
  tasks:
    - name: Check if Server is Alive
      ping:
      tags: check

    - name: Install Apache packages
      yum:
        name: httpd
        state: present

    - name: ensure Httpd is running
      service:
        name: httpd
        enabled: yes
        state: started

    - name: Open port 80 for http access
      firewalld:
        service: http
        permanent: true
        state: enabled

    - name: Restart the firewalld service to load in the firewall changes
      service:
        name: firewalld
        state: restarted